FROM node:20.17.0-bullseye AS prod

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile=false

ENV PATH="./node_modules/.bin:$PATH"

COPY . .

RUN npx prisma generate

EXPOSE 8000

CMD ["pnpm", "start:dev"]
