version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: vamosexpeditions-backend-app_v1
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - COOKIE_EXPIRATION=${COOKIE_EXPIRATION}
      - TOKEN_COOKIE_NAME=${TOKEN_COOKIE_NAME}
      - REFRESH_TOKEN_COOKIE_NAME=${REFRESH_TOKEN_COOKIE_NAME}
      - EXPIRATION_TOKEN_COOKIE_NAME=${EXPIRATION_TOKEN_COOKIE_NAME}
      - CLIENT_URL=${CLIENT_URL}
      - JWT_DURATION=${JWT_DURATION}
      - JWT_SEED=${JWT_SEED}
      - POSTGRES_URL=${POSTGRES_URL}
      - EXTERNAL_API_COUNTRY_URL=${EXTERNAL_API_COUNTRY_URL}
      - MAILER_SERVICE=${MAILER_SERVICE}
      - MAILER_EMAIL=${MAILER_EMAIL}
      - MAILER_SECRET_KEY=${MAILER_SECRET_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_FOLDER=${CLOUDINARY_FOLDER}
     
